# managed-by-cf-init
name = "newsdigest"
main = "worker/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
AI_GATEWAY_URL = "https://gateway.ai.cloudflare.com/v1/4ade94c28880b53876bf8cd0c604e426/newsdigest/google-ai-studio"

[[d1_databases]]
binding = "DB"
database_name = "newsdigest"
database_id = "a5893b04-f363-4e19-9395-7e193a564bbd"

[[kv_namespaces]]
binding = "NEWS_DIGEST_KV"
id = "40f887dd37bb47ddba8b7676f1021131"

[triggers]
crons = ["0 */3 * * *", "0 1 * * *", "*/30 * * * *", "30 23 * * *"]

[[queues.producers]]
queue = "article-content-queue"
binding = "CONTENT_QUEUE"

[[queues.consumers]]
queue = "article-content-queue"
max_batch_size = 1
max_batch_timeout = 5
max_retries = 1
dead_letter_queue = "article-content-dlq"
